Update action.yml

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -65,14 +65,14 @@ jobs:
           make
           sudo make install
           tcc -v
-          echo TRY-COMPILE-LOGIN
-          rm attack-tmp*
+          # echo TRY-COMPILE-LOGIN
+          # rm attack-tmp*
           # rm attack2-tmp*
-          tcc login.c
+          # tcc login.c
           # ./a.out <<< hackerken
-          if ./a.out <<< hackerken | grep -q 'fail'; then exit 1; fi
-          if ./a.out <<< $'admin\npassword' | grep -q 'fail'; then exit 1; fi
-          if ./a.out <<< $'admin\npa55word' | grep -q 'success'; then exit 1; fi
+          # if ./a.out <<< hackerken | grep -q 'fail'; then exit 1; fi
+          # if ./a.out <<< $'admin\npassword' | grep -q 'fail'; then exit 1; fi
+          # if ./a.out <<< $'admin\npa55word' | grep -q 'success'; then exit 1; fi
           echo DONE
 
           
